### ISSUE TITLE
Улучшить пример критерия

### ISSUE THREAD

**Issue by zeckson** [htmlacademy/intensive-ecmascript-criteria#2]
https://github.com/htmlacademy/intensive-ecmascript-criteria/blob/65fd5a15d7ce4bc7bcd06de3a3a4dbcc593c0dd3/index.md#В-случае-если-одинаковый-код-повторяется-в-нескольких-модулях-повторяющаяся-часть-вынесена-в-отдельный-модуль

**Comment by o0** [comment]
Не помню совершенно про что это:)

**Comment by zeckson** [comment]
Я тоже
